### PR TITLE
Set a default region because boto3 barfs without it

### PR DESCRIPTION
**Pull request by lucas42**

### CODE REVIEW

**Comment by GeoffThorpeFT** [comment]
Can you be more specific about how boto3 fails?  The env settings you have highlighted are specific to the stream processing - so are you suggesting stream processing fails without a region?

**Comment by lucas42** [comment]
Boto throws an exception saying the region isn't set, causing the entire app not to start.  There may be a better way to handle this (for example not even instantiating boto if the relevant vars aren't set), but this was the simplest way to get anything running on my local machine.

**Comment by GeoffThorpeFT** [comment]
I have added an extra item of code into this request, check the env variables during the stream opening. The real error you are seeing is that the stream is opened even when the variables are not set

**Comment by lucas42** [comment]
Cool, that looks like a better solution.  :+1:

**Pull request merged**
