### PR TITLE
Add some docs.

### PR DESCRIPTION
**Pull request by lucas42**
I've added some docs to most of the endpoints.

### CODE REVIEW

**Comment by GeoffThorpeFT** [comment]
The above highlights the need to change the names of the methods within the code - as those are the names shown to the user in the doc text. Why not ensure natural case whilst doing so? Pylint suggests its good practice; thus losing the lowercase character at the start of each name.

**Comment by GeoffThorpeFT** [comment]
A number of the improved names end in 'View' but they allow the user to do a lot more than view the data. I suggest we remove 'view' from the methods that allow update and delete. e.g. attributeTypeView becomes AttributeType or AttributeDefinition

**Comment by GeoffThorpeFT** [comment]
The help text for many of the endpoints now includes explicit references to the names of the parameters used by those endpoints - e.d. dataItemID and dataItemType, At the point the user has read the text they will not always be unaware of those parameter names. listRelationshipsBySubjectAndTypeView is one example.

**Comment by lucas42** [comment]
@GeoffThorpeFT In django terminology these are all 'views' (hence inclusion in the views.py file).  Removing the -View suffix would cause ambiguity with the models (eg RelationshipType)

**Pull request merged**
